### ISSUE TITLE
在mac os下ParkingLotEditor运行一段时间就会崩溃

### ISSUE THREAD

**Issue by choizhang** [DCMMC/ParkingLot#2]
如题

**Comment by DCMMC** [comment]
因为 ParkingLotEdition 是基于一个 Qt5 写的商场建模软件的基础上修改制作的, 所以原 repo 的作者写了很多的 bug. 加之我对 Qt5/C++ 不够熟练, 时间有限, 所以软件存在很多逻辑上考虑不周到/C++ 内存管理的问题. 如果题主有时间, 可以发一下详细一点的崩溃日志, 然后最好自己用 IDE(推荐 Clion) debug 看一看. 因为本人测试平台是在 ArchLinux 上, 到时候有时间我会在 macOS 平台上测试一下.

**Comment by yorick520** [comment]
点击链接加入群聊【indoor3D】：https://jq.qq.com/?_wv=1027&k=5RDyUMF

作者，有无发现经常编译器编译出来数据文件加载错误。出现与原有格式不一致

**Comment by DCMMC** [comment]
这种情况没遇到过诶
